-- MySQL Script generated by MySQL Workbench
-- sáb 12 out 2019 19:53:09 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema vadebike
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vadebike
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vadebike` DEFAULT CHARACTER SET latin1 ;
USE `vadebike` ;

-- -----------------------------------------------------
-- Table `vadebike`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vadebike`.`endereco` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(255) NULL DEFAULT NULL,
  `numero` VARCHAR(255) NULL DEFAULT NULL,
  `complemento` VARCHAR(255) NULL DEFAULT NULL,
  `bairro` VARCHAR(255) NULL DEFAULT NULL,
  `cidade` VARCHAR(255) NULL DEFAULT NULL,
  `estado` VARCHAR(255) NULL DEFAULT NULL,
  `cep` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `vadebike`.`locador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vadebike`.`locador` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  `cpf` VARCHAR(255) NULL DEFAULT NULL,
  `idEndereco` INT(11) NOT NULL,
  `celular` VARCHAR(255) NULL DEFAULT NULL,
  `login` VARCHAR(255) NULL DEFAULT NULL,
  `senha` VARCHAR(255) NULL DEFAULT NULL,
  `dataCadastro` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_locador_endereco` (`idEndereco` ASC) VISIBLE,
  CONSTRAINT `fk_locador_endereco`
    FOREIGN KEY (`idEndereco`)
    REFERENCES `vadebike`.`endereco` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `vadebike`.`bicicleta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vadebike`.`bicicleta` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `idLocador` INT(11) NOT NULL,
  `modelo` VARCHAR(255) NULL DEFAULT NULL,
  `ano` VARCHAR(255) NULL DEFAULT NULL,
  `valorDeAluguel` VARCHAR(255) NULL DEFAULT NULL,
  `acessorios` VARCHAR(255) NULL DEFAULT NULL,
  `disponivel` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bicicleta_locador` (`idLocador` ASC) VISIBLE,
  CONSTRAINT `fk_bicicleta_locador`
    FOREIGN KEY (`idLocador`)
    REFERENCES `vadebike`.`locador` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `vadebike`.`locatario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vadebike`.`locatario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  `cpf` VARCHAR(255) NULL DEFAULT NULL,
  `idEndereco` INT(11) NOT NULL,
  `celular` VARCHAR(255) NULL DEFAULT NULL,
  `login` VARCHAR(255) NULL DEFAULT NULL,
  `senha` VARCHAR(255) NULL DEFAULT NULL,
  `dataCadastro` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_locatario_endereco` (`idEndereco` ASC) VISIBLE,
  CONSTRAINT `fk_locatario_endereco`
    FOREIGN KEY (`idEndereco`)
    REFERENCES `vadebike`.`endereco` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `vadebike`.`aluguel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vadebike`.`aluguel` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `idLocador` INT(11) NOT NULL,
  `idLocatario` INT(11) NOT NULL,
  `idBicicleta` INT(11) NOT NULL,
  `dtInicio` DATE NULL DEFAULT NULL,
  `dtFimPrevisto` DATE NULL DEFAULT NULL,
  `dtFimRealizado` DATE NULL DEFAULT NULL,
  `valorPrevisto` DOUBLE NULL DEFAULT NULL,
  `valorMulta` DOUBLE NULL DEFAULT '0',
  `valorFinal` DOUBLE NULL DEFAULT NULL,
  `pendente` TINYINT(1) NULL DEFAULT '1',
  `cancelado` TINYINT(1) NULL DEFAULT '0',
  `iniciado` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `fk_aluguel_locador` (`idLocador` ASC) VISIBLE,
  INDEX `fk_aluguel_locatario` (`idLocatario` ASC) VISIBLE,
  INDEX `fk_aluguel_bicicleta` (`idBicicleta` ASC) VISIBLE,
  CONSTRAINT `fk_aluguel_bicicleta`
    FOREIGN KEY (`idBicicleta`)
    REFERENCES `vadebike`.`bicicleta` (`id`),
  CONSTRAINT `fk_aluguel_locador`
    FOREIGN KEY (`idLocador`)
    REFERENCES `vadebike`.`locador` (`id`),
  CONSTRAINT `fk_aluguel_locatario`
    FOREIGN KEY (`idLocatario`)
    REFERENCES `vadebike`.`locatario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `vadebike`.`avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vadebike`.`avaliacao` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `idAluguel` INT(11) NOT NULL,
  `notaDoLocadorParaLocatario` DOUBLE NULL DEFAULT NULL,
  `notaDoLocatarioParaLocador` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_avaliacao_aluguel` (`idAluguel` ASC) VISIBLE,
  CONSTRAINT `fk_avaliacao_aluguel`
    FOREIGN KEY (`idAluguel`)
    REFERENCES `vadebike`.`aluguel` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `vadebike`.`carteiraLocador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vadebike`.`carteiraLocador` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `idLocador` INT(11) NOT NULL,
  `saldo` DOUBLE NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `fk_carteiraLocador_locador` (`idLocador` ASC) VISIBLE,
  CONSTRAINT `fk_carteiraLocador_locador`
    FOREIGN KEY (`idLocador`)
    REFERENCES `vadebike`.`locador` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `vadebike`.`carteiraLocatario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vadebike`.`carteiraLocatario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `idLocatario` INT(11) NOT NULL,
  `multaAcumulada` DOUBLE NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `fk_carteiraLocatario_locatario` (`idLocatario` ASC) VISIBLE,
  CONSTRAINT `fk_carteiraLocatario_locatario`
    FOREIGN KEY (`idLocatario`)
    REFERENCES `vadebike`.`locatario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
